development:
  secret_key_base: a455553900ff0f1cff4aea3c846db75f9780dbb8e1d6c305e051d03f5269d976d8c0a12832186362fd394bf0cf0afec1ebc8ea8bb108543daa9254bd4928dfb3
  token_es_priv: "-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIBHSbdTKy+CBsNXulwj5aAUaL8nU3EGrQSTqS0nLpXr0WGBRxBzixM\nDvFMjC1p5pUirqwL5xaBdV/uCh4WFtQ1xGagBwYFK4EEACOhgYkDgYYABAE5bdY3\nwRwFMQMAoFsbZ+j2AEDzkHJDuxNG1aFv49aC6HhKQOHHHCQs4mZPGmTsH+mEJEwC\nCCOG8DjXQuI5+SqlqADJ0+E8WqyR+FJrsX/DhbcZ5XAZUSfnT8E0QXBQ7yloj6tD\nVvu0UO+oA7X/dgVKitGG8R2W2/KQicJPTZC9kC3mpg==\n-----END EC PRIVATE KEY-----\n"
  jwt_issuer: "sombra_development"

test:
  secret_key_base: a07db8c90bd628ec8ba7841dd056749f25f796d19e0bb393343b64f7acfb5199e3e675891337417dbc6bdb4133d5be6efee2df560791e7fdfb11feacd375708a
  token_es_priv: "-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIB9VRWLwgsPna4OdMZ1YE+/lfzBKgBKlaA7U7jq9vciOacgET6Yy+r\nTQ8NpQUv9xoCxc+T8v/U8oWMNqePT7nW90egBwYFK4EEACOhgYkDgYYABAEU6RDT\nVDXXyxvOOaF/r6M2kUIq69fhdP4dGtfGD90L/kV2qQZLMFxs5UVOvE4laoQURDGD\nNnOibbXWwASBry0WawBl4XDrFIjp5hB8OZm1E9/g72ci5YRfsjfw4NdpWs0ZZyuH\nnbvrxLkr5LF0oaeIGbtJWCK/n2YwI6xkKY3vigxQQA==\n-----END EC PRIVATE KEY-----\n"
  jwt_issuer: "sombra_test"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"
  token_es_priv: "<%= ENV["SOMBRA_TOKEN_SECRET_PRIVATE"].gsub(/[\r\n]+/, '\n') %>"
  jwt_issuer: "<%= ENV["SOMBRA_TOKEN_ISSUER"] %>"
